# Generated by Django 5.0.4 on 2024-08-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_name',
            new_name='username',
        ),
    ]
