# Generated by Django 5.0.4 on 2024-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetail',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
