# Generated by Django 5.0.4 on 2024-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_healthdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
