# Generated by Django 5.0.4 on 2024-10-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_healthdetail_fitness_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdetail',
            name='email',
        ),
        migrations.AlterField(
            model_name='healthdetail',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
