# Generated by Django 5.0.4 on 2024-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_healthdetail_fitness_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdetail',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'weight_loss'), ('muscle_gain', 'muscle_gain'), ('maintenance', 'maintenance')], max_length=11),
        ),
    ]
