# Generated by Django 5.0.4 on 2024-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_routine_exercise_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetail',
            name='workout_streak',
            field=models.IntegerField(default=0),
        ),
    ]
