# Generated by Django 5.0.4 on 2024-10-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_exercise_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(max_length=10),
        ),
    ]
