# Generated by Django 5.0.4 on 2024-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_exercise_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
