# Generated by Django 5.0.4 on 2024-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_dailyweight_user_alter_healthdetail_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='steps_completed',
            field=models.BooleanField(default=False),
        ),
    ]
