# Generated by Django 5.0.4 on 2024-10-31 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_day_steps_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetail',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 10, 20, 0, 0)),
            preserve_default=False,
        ),
    ]
