# Generated by Django 5.0.4 on 2024-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_dailyweight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetail',
            name='subscription_tier',
            field=models.CharField(choices=[('FitStarter', 'FitStarter'), ('StrengthMaster', 'StrengthMaster'), ('FitnessTitan', 'FitnessTitan')], default='FitStarter', max_length=14),
        ),
    ]
